### ISSUE TITLE
Remove Filepicker keys from config..

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/webpack-config#31]
... they should be moved to TravisCI's config file as encrypted values.

**Comment by vikasrohit** [comment]
@parthshah we can encrypt the keys, however, they would still be visible publicly because our github repo is public and anyone can access the travis build logs of the repo. I tried that in incognito window and I am able to view the unencrypted keys in the logs.

However, I think it still makes sense to encrypt it at least in github so that bots can not use it programmatically. Further, while we are doing this, we can also do the same for AUTH0 ids and secrets.

**Comment by parthshah** [comment]
TravisCI isn't the one printing the values. 
![image](https://cloud.githubusercontent.com/assets/1987710/22560698/6a1b1910-e92a-11e6-8255-a70538fd7e28.png)

I believe it's coming from our webpack config. We should disable that as well.

**Comment by vikasrohit** [comment]
Thanks for catching that @parthshah Removed console logging of env variables for QA and PROD builds. However, I think still any public user can check values of encrypted env variables e.g. fork the public repo and update its webpack config to again print the env variables. :(

**Comment by vikasrohit** [comment]
As discussed, I have removed the logging of env variables completely no matter which env build is running for.
